### ISSUE TITLE
I want to see a list of all the polling locations so that I can decide where to vote.

### ISSUE THREAD

**Issue by goizueta** [emergentworks/poll2poll#1]
When I am looking to vote I want to see a list of all the polling locations so that I can decide where to vote.

Why
As a person who likes to vote
I want to see a list of polling locations
So that I can decide where I want to vote

Acceptance Criteria
Given I have downloaded the app
when I open the app
then I see a list of polling locations

Notes:
We have to figure out where the list of polling locations is coming from.
Is it through data sources?

Track down the list and put it into a spreadsheet so that engineers can put it into the database.

**Comment by armyregime** [comment]
When I am looking to vote I want to see a list of all the polling locations so that I can decide where to vote.

Why
As a person who likes to vote
I want to see a list of polling locations
So that I can decide where I want to vote

Acceptance Criteria
Given I have downloaded the app
when I open the app
then I see a list of polling locations

Notes:
We have to figure out where the list of polling locations is coming from.
Is it through data sources?

Track down the list and put it into a spreadsheet so that engineers can put it into the database.

**Comment by armyregime** [comment]
Hey team, This is the link to the design of the Poll 2 Poll application via Figma.

https://www.figma.com/file/tQfdp4ayv1741ZbKki0SwI/Poll2Poll-Wireframes?node-id=0%3A1

**Comment by armyregime** [comment]
Hey, Fei had an idea that she sent via email for a way for us to find polling locations by zip code.

Allowing users to pull up a list of relevant polling locations when they enter their zip code
- Getting access to an open database of poll locations based on zip code. I'm hoping we can find an API that will work for our purposes, and a quick search has to lead me to Google's Civic Information API. OR, there is an embeddable widget from something called the Poll Site Locator.
- Dierdre will share 2-3 screens to support this above key interaction

**Comment by dierdre3000** [comment]
Hi team,

Sharing an updated link to the key interaction:

https://www.figma.com/file/tQfdp4ayv1741ZbKki0SwI/Poll2Poll-Wireframes?node-id=98%3A198 

Thanks!

Dierdre

> Hey team, This is the link to the design of the Poll 2 Poll application via Figma.
> 
> https://www.figma.com/file/tQfdp4ayv1741ZbKki0SwI/Poll2Poll-Wireframes?node-id=0%3A1

**Comment by armyregime** [comment]
Hey, @goizueta Can we delete this story, please. Thanks.
